import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/favicon.ico',
          '/favicon.png',
          '/favicon-48x48.png',
          '/favicon-32x32.png',
          '/favicon-16x16.png',
          '/icon.png',
          '/apple-touch-icon.png',
          '/manifest.json',
          '/business/',
          '/category/',
          '/services',
          '/food',
          '/hotels',
          '/resorts',
          '/properties',
          '/jobs',
          '/hire-vehicle',
          '/blood-donation',
          '/home-services',
          '/creators',
          '/advertise',
        ],
        disallow: [
          '/admin/',
          '/adminmb/',
          '/dashboard/',
          '/api/',
          '/search?', // Don't let search query spam consume crawl budget
          '/*?*sort=*',
          '/*?*filter=*',
        ],
      },
      {
        userAgent: ['Googlebot', 'Bingbot', 'Googlebot-Image', 'Googlebot-Favicon', 'Google-Favicon'],
        allow: [
          '/',
          '/favicon.ico',
          '/favicon.png',
          '/favicon-48x48.png',
          '/favicon-32x32.png',
          '/favicon-16x16.png',
          '/icon.png',
          '/apple-touch-icon.png',
          '/manifest.json',
          '/business/',
          '/category/',
          '/services',
          '/food',
          '/hotels',
          '/resorts',
          '/properties',
          '/jobs',
          '/hire-vehicle',
          '/blood-donation',
        ],
        disallow: [
          '/admin/',
          '/adminmb/',
          '/dashboard/',
          '/api/',
          '/search?',
        ],
      },
    ],
    sitemap: 'https://majhboisar.in/sitemap.xml',
    host: 'https://majhboisar.in',
  };
}
